FROM golang:alpine

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN apk add masscan libpcap-dev libc-dev gcc
RUN go mod download && go mod verify

COPY main.go .
COPY tasks ./tasks
COPY utils ./utils
COPY types ./types
COPY .env .env

RUN go build -o scanner main.go

CMD ["./scanner"]
