FROM golang:alpine

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY worker/worker.go main.go
COPY tasks ./tasks
COPY .env .env

RUN go build -o worker main.go

CMD ["./worker"]
